### ISSUE TITLE
CI image in README not visible

### ISSUE THREAD

**Issue by peckjon** [jfrog/connect-deploy-update#1]
README contains [a line](https://github.com/jfrog/connect-deploy-update/blob/5d066ce4c58043c8c17cbf2483e10d84798e8b4e/README.md?plain=1#L3C1-L3C168) referencing an SVG which is not publicly visible, breaking the view [in the repo](https://github.com/jfrog/connect-deploy-update) and [on the Actions marketplace](https://github.com/marketplace/actions/deploy-update)

```markdown
[![ci](https://github.com/upswift/connect-deploy-update/actions/workflows/ci.yml/badge.svg)](https://github.com/upswift/connect-deploy-update/actions/workflows/ci.yml)
```

![Image](https://github.com/user-attachments/assets/8d8f6d84-2069-4a01-acae-82da3897e783)

**Comment by maxyurk** [comment]
fixed, thanks!
